import { readFile, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const root = fileURLToPath(new URL('../', import.meta.url));
const html = await readFile(path.join(root, 'index.html'), 'utf8');
assert.equal((html.match(/<h1[ >]/g)||[]).length, 1, 'One primary heading');
const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]);
assert.equal(ids.length, new Set(ids).size, 'Unique IDs');
for (const [,target] of html.matchAll(/href="#([^"]+)"/g)) assert(ids.includes(target), `Missing anchor: ${target}`);
for (const [,asset] of html.matchAll(/(?:src|href)="((?:assets\/|styles\.css|script\.js)[^"]*)"/g)) assert((await stat(path.join(root, asset))).size > 0, `Missing asset: ${asset}`);
for (const [,tag] of html.matchAll(/(<img\b[^>]*>)/g)) assert(/\balt="[^"]*"/.test(tag), 'Image must have alt text');
const json = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
assert.equal(JSON.parse(json[1])['@type'], 'SoftwareApplication');
assert(html.includes('https://tawqee.forgrise.com/'), 'Canonical URL');
assert(html.includes('sales@forgrise.com'), 'Contact email');
assert(html.includes('preload="none"'), 'Video must not download on page load');
assert(html.includes('kind="captions"'), 'Video captions');
console.log('Passed: local assets, anchors, unique IDs, image alt text, structured data, canonical, contact, and video loading/accessibility.');
